Document: armoreproxy
Title: Debian armoreproxy Manual
Author: <insert document author here>
Abstract: This manual describes what armoreproxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/armoreproxy/armoreproxy.sgml.gz

Format: postscript
Files: /usr/share/doc/armoreproxy/armoreproxy.ps.gz

Format: text
Files: /usr/share/doc/armoreproxy/armoreproxy.text.gz

Format: HTML
Index: /usr/share/doc/armoreproxy/html/index.html
Files: /usr/share/doc/armoreproxy/html/*.html
