Document: armoreconfig
Title: Debian armoreconfig Manual
Author: <insert document author here>
Abstract: This manual describes what armoreconfig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/armoreconfig/armoreconfig.sgml.gz

Format: postscript
Files: /usr/share/doc/armoreconfig/armoreconfig.ps.gz

Format: text
Files: /usr/share/doc/armoreconfig/armoreconfig.text.gz

Format: HTML
Index: /usr/share/doc/armoreconfig/html/index.html
Files: /usr/share/doc/armoreconfig/html/*.html
