Document: armoreczmq
Title: Debian armoreczmq Manual
Author: <insert document author here>
Abstract: This manual describes what armoreczmq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/armoreczmq/armoreczmq.sgml.gz

Format: postscript
Files: /usr/share/doc/armoreczmq/armoreczmq.ps.gz

Format: text
Files: /usr/share/doc/armoreczmq/armoreczmq.text.gz

Format: HTML
Index: /usr/share/doc/armoreczmq/html/index.html
Files: /usr/share/doc/armoreczmq/html/*.html
