Document: libsodium18
Title: Debian libsodium18 Manual
Author: <insert document author here>
Abstract: This manual describes what libsodium18 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsodium18/libsodium18.sgml.gz

Format: postscript
Files: /usr/share/doc/libsodium18/libsodium18.ps.gz

Format: text
Files: /usr/share/doc/libsodium18/libsodium18.text.gz

Format: HTML
Index: /usr/share/doc/libsodium18/html/index.html
Files: /usr/share/doc/libsodium18/html/*.html
