# This file was automatically generated by bifcl from /home/armore/projects/bro-statsd-plugin/src/statsd.bif (plugin mode).

export {
global statsd_increment: function(s: string , c: count ): any ;

} # end of export section
module GLOBAL;
