#! /bin/bash

# University of Illinois/NCSA Open Source License
# Copyright (c) 2015 Information Trust Institute
# All rights reserved.
#
# Developed by:
#
# Information Trust Institute
# University of Illinois
# http://www.iti.illinois.edu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal with
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimers. Redistributions in binary form must
# reproduce the above copyright notice, this list of conditions and the following
# disclaimers in the documentation and/or other materials provided with the
# distribution.
#
# Neither the names of Information Trust Institute, University of Illinois, nor
# the names of its contributors may be used to endorse or promote products derived
# from this Software without specific prior written permission.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE CONTRIBUTORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
#
#

###############################################################################
#Initialization script for ARMORE NODE

#Please note, this is for a generic environment
#you will have to build and insmod the correct module for your card
###############################################################################

environment_check ()
{

    #Check if user is root
    if [ "$EUID" -ne 0 ];
    then 
        echo "Please run this script as root"
        exit
    fi
}

env_init()
{

    PBRICKS=$PWD/packet-bricks/bin
    PBRICKCFG=$PWD/packet-bricks/scripts
    BUILD=$PWD

    #Lets get all the bricks binaries into our path
    export PATH=$PATH:$PBRICKS

    #start up vmwares kmods 
    vmware-user  

    #This will stop the OS from doing an autoconf or dhcp on the interfaces 
    service network-manager stop 

    #We will want to run our card in this mode to enable sniffing
    ifconfig eth0 promisc

    #Make sure to comment out the right module for your card as well. netmap.ko is needed bare minimum
    insmod $BUILD/kmods/netmap.ko

    printf "Packet-Bricks and Bro should now be able to be started \n"
}


environment_check
env_init





