Document: armorelibcurve
Title: Debian armorelibcurve Manual
Author: <insert document author here>
Abstract: This manual describes what armorelibcurve is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/armorelibcurve/armorelibcurve.sgml.gz

Format: postscript
Files: /usr/share/doc/armorelibcurve/armorelibcurve.ps.gz

Format: text
Files: /usr/share/doc/armorelibcurve/armorelibcurve.text.gz

Format: HTML
Index: /usr/share/doc/armorelibcurve/html/index.html
Files: /usr/share/doc/armorelibcurve/html/*.html
